// Generated by ../../scripts/generate-traces.ts. Do not edit by hand.
import type { TraceCase, TraceMeta } from "./trace-types";

export const traceMeta: TraceMeta = {
  "model": "glm-5.2",
  "generatedAt": "2026-08-09T11:08:59.139Z",
  "liveGenerated": true
};

export const traceCases: TraceCase[] = [
  {
    "id": "plain-text",
    "number": "01",
    "title": "没有 tool_call",
    "summary": "模型只返回文本，循环一轮结束。",
    "prompt": "只回答这一句：没有 tool_call，Agent Loop 就会结束。",
    "model": "glm-5.2",
    "outcome": "一条 assistant message，随后 end_turn。",
    "steps": [
      {
        "id": "input",
        "label": "用户消息进入 Context",
        "detail": "CLI 先把这一轮输入追加到 messages，随后把 Context 交给 runAgent()。",
        "kind": "input",
        "source": {
          "file": "src/cli.ts",
          "line": 49
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户要求回答，答案保持一句话。",
          "messages": [
            {
              "role": "user",
              "content": "只回答这一句：没有 tool_call，Agent Loop 就会结束。"
            }
          ]
        }
      },
      {
        "id": "event-1",
        "label": "模型流式输出文本",
        "detail": "stream() 产生 text_delta，agent 将它转成 assistant_text 发给界面。",
        "kind": "stream",
        "source": {
          "file": "src/agent.ts",
          "line": 101
        },
        "event": {
          "type": "assistant_text",
          "delta": "没有 tool_call，Agent Loop 就会结束。"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户要求回答，答案保持一句话。",
          "messages": [
            {
              "role": "user",
              "content": "只回答这一句：没有 tool_call，Agent Loop 就会结束。"
            }
          ]
        }
      },
      {
        "id": "context-2",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户要求回答，答案保持一句话。",
          "messages": [
            {
              "role": "user",
              "content": "只回答这一句：没有 tool_call，Agent Loop 就会结束。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "text",
                  "text": "没有 tool_call，Agent Loop 就会结束。"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-3",
        "label": "本轮结束：end_turn",
        "detail": "这一轮没有新的 tool_call，Agent Loop 正常退出。",
        "kind": "end",
        "source": {
          "file": "src/agent.ts",
          "line": 141
        },
        "event": {
          "type": "turn_end",
          "stopReason": "end_turn"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户要求回答，答案保持一句话。",
          "messages": [
            {
              "role": "user",
              "content": "只回答这一句：没有 tool_call，Agent Loop 就会结束。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "text",
                  "text": "没有 tool_call，Agent Loop 就会结束。"
                }
              ]
            }
          ]
        }
      }
    ]
  },
  {
    "id": "read-file",
    "number": "02",
    "title": "读取一个文件",
    "summary": "模型调用 read_file，把结果放回 Context，再完成回答。",
    "prompt": "使用 read_file 读取 /workspace/hello.txt，告诉我第一行。不要猜。",
    "model": "glm-5.2",
    "outcome": "一次工具往返，两轮 LLM 请求。",
    "steps": [
      {
        "id": "input",
        "label": "用户消息进入 Context",
        "detail": "CLI 先把这一轮输入追加到 messages，随后把 Context 交给 runAgent()。",
        "kind": "input",
        "source": {
          "file": "src/cli.ts",
          "line": 49
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须使用提供的工具完成任务，工具返回后用一句话回答。",
          "messages": [
            {
              "role": "user",
              "content": "使用 read_file 读取 /workspace/hello.txt，告诉我第一行。不要猜。"
            }
          ]
        }
      },
      {
        "id": "event-1",
        "label": "模型调用 read_file",
        "detail": "agent 收集工具名和参数，同时发出 tool_call 事件。",
        "kind": "tool",
        "source": {
          "file": "src/agent.ts",
          "line": 104
        },
        "event": {
          "type": "tool_call",
          "id": "call_e4e99320de224ef7b703e1ef",
          "name": "read_file",
          "args": {
            "path": "/workspace/hello.txt"
          }
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须使用提供的工具完成任务，工具返回后用一句话回答。",
          "messages": [
            {
              "role": "user",
              "content": "使用 read_file 读取 /workspace/hello.txt，告诉我第一行。不要猜。"
            }
          ]
        }
      },
      {
        "id": "context-2",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须使用提供的工具完成任务，工具返回后用一句话回答。",
          "messages": [
            {
              "role": "user",
              "content": "使用 read_file 读取 /workspace/hello.txt，告诉我第一行。不要猜。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_e4e99320de224ef7b703e1ef",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/hello.txt"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-3",
        "label": "read_file 返回结果",
        "detail": "工具已经执行完，结果先作为 AgentEvent 发出，随后写回 Context。",
        "kind": "tool",
        "source": {
          "file": "src/agent.ts",
          "line": 132
        },
        "event": {
          "type": "tool_result",
          "id": "call_e4e99320de224ef7b703e1ef",
          "name": "read_file",
          "result": "alpha\nbeta\ngamma\n"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须使用提供的工具完成任务，工具返回后用一句话回答。",
          "messages": [
            {
              "role": "user",
              "content": "使用 read_file 读取 /workspace/hello.txt，告诉我第一行。不要猜。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_e4e99320de224ef7b703e1ef",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/hello.txt"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "id": "context-4",
        "label": "tool_result 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 172
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须使用提供的工具完成任务，工具返回后用一句话回答。",
          "messages": [
            {
              "role": "user",
              "content": "使用 read_file 读取 /workspace/hello.txt，告诉我第一行。不要猜。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_e4e99320de224ef7b703e1ef",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/hello.txt"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_e4e99320de224ef7b703e1ef",
                  "content": "alpha\nbeta\ngamma\n"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-5",
        "label": "模型流式输出文本",
        "detail": "stream() 产生 text_delta，agent 将它转成 assistant_text 发给界面。",
        "kind": "stream",
        "source": {
          "file": "src/agent.ts",
          "line": 101
        },
        "event": {
          "type": "assistant_text",
          "delta": "该文件的第一行是 **alpha**。"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须使用提供的工具完成任务，工具返回后用一句话回答。",
          "messages": [
            {
              "role": "user",
              "content": "使用 read_file 读取 /workspace/hello.txt，告诉我第一行。不要猜。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_e4e99320de224ef7b703e1ef",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/hello.txt"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_e4e99320de224ef7b703e1ef",
                  "content": "alpha\nbeta\ngamma\n"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "context-6",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须使用提供的工具完成任务，工具返回后用一句话回答。",
          "messages": [
            {
              "role": "user",
              "content": "使用 read_file 读取 /workspace/hello.txt，告诉我第一行。不要猜。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_e4e99320de224ef7b703e1ef",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/hello.txt"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_e4e99320de224ef7b703e1ef",
                  "content": "alpha\nbeta\ngamma\n"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "text",
                  "text": "该文件的第一行是 **alpha**。"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-7",
        "label": "本轮结束：end_turn",
        "detail": "这一轮没有新的 tool_call，Agent Loop 正常退出。",
        "kind": "end",
        "source": {
          "file": "src/agent.ts",
          "line": 141
        },
        "event": {
          "type": "turn_end",
          "stopReason": "end_turn"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须使用提供的工具完成任务，工具返回后用一句话回答。",
          "messages": [
            {
              "role": "user",
              "content": "使用 read_file 读取 /workspace/hello.txt，告诉我第一行。不要猜。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_e4e99320de224ef7b703e1ef",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/hello.txt"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_e4e99320de224ef7b703e1ef",
                  "content": "alpha\nbeta\ngamma\n"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "text",
                  "text": "该文件的第一行是 **alpha**。"
                }
              ]
            }
          ]
        }
      }
    ]
  },
  {
    "id": "edit-and-check",
    "number": "03",
    "title": "修改并验证",
    "summary": "模型先编辑文件，再读回来确认修改。",
    "prompt": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。",
    "model": "glm-5.2",
    "outcome": "edit 和 read_file 串成一条多工具路径。",
    "steps": [
      {
        "id": "input",
        "label": "用户消息进入 Context",
        "detail": "CLI 先把这一轮输入追加到 messages，随后把 Context 交给 runAgent()。",
        "kind": "input",
        "source": {
          "file": "src/cli.ts",
          "line": 49
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            }
          ]
        }
      },
      {
        "id": "event-1",
        "label": "模型调用 edit",
        "detail": "agent 收集工具名和参数，同时发出 tool_call 事件。",
        "kind": "tool",
        "source": {
          "file": "src/agent.ts",
          "line": 104
        },
        "event": {
          "type": "tool_call",
          "id": "call_d00d9edb9e2145ef90064c64",
          "name": "edit",
          "args": {
            "path": "/workspace/config.ts",
            "old_string": "retries = 2",
            "new_string": "retries = 3"
          }
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            }
          ]
        }
      },
      {
        "id": "context-2",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-3",
        "label": "edit 返回结果",
        "detail": "工具已经执行完，结果先作为 AgentEvent 发出，随后写回 Context。",
        "kind": "tool",
        "source": {
          "file": "src/agent.ts",
          "line": 132
        },
        "event": {
          "type": "tool_result",
          "id": "call_d00d9edb9e2145ef90064c64",
          "name": "edit",
          "result": "edited /workspace/config.ts: replaced 11 chars"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "id": "context-4",
        "label": "tool_result 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 172
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_d00d9edb9e2145ef90064c64",
                  "content": "edited /workspace/config.ts: replaced 11 chars"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-5",
        "label": "模型调用 read_file",
        "detail": "agent 收集工具名和参数，同时发出 tool_call 事件。",
        "kind": "tool",
        "source": {
          "file": "src/agent.ts",
          "line": 104
        },
        "event": {
          "type": "tool_call",
          "id": "call_c497376af2ab40c19a013962",
          "name": "read_file",
          "args": {
            "path": "/workspace/config.ts"
          }
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_d00d9edb9e2145ef90064c64",
                  "content": "edited /workspace/config.ts: replaced 11 chars"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "context-6",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_d00d9edb9e2145ef90064c64",
                  "content": "edited /workspace/config.ts: replaced 11 chars"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_c497376af2ab40c19a013962",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/config.ts"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-7",
        "label": "read_file 返回结果",
        "detail": "工具已经执行完，结果先作为 AgentEvent 发出，随后写回 Context。",
        "kind": "tool",
        "source": {
          "file": "src/agent.ts",
          "line": 132
        },
        "event": {
          "type": "tool_result",
          "id": "call_c497376af2ab40c19a013962",
          "name": "read_file",
          "result": "export const retries = 3\n"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_d00d9edb9e2145ef90064c64",
                  "content": "edited /workspace/config.ts: replaced 11 chars"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_c497376af2ab40c19a013962",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/config.ts"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "id": "context-8",
        "label": "tool_result 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 172
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_d00d9edb9e2145ef90064c64",
                  "content": "edited /workspace/config.ts: replaced 11 chars"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_c497376af2ab40c19a013962",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/config.ts"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_c497376af2ab40c19a013962",
                  "content": "export const retries = 3\n"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-9",
        "label": "模型流式输出文本",
        "detail": "stream() 产生 text_delta，agent 将它转成 assistant_text 发给界面。",
        "kind": "stream",
        "source": {
          "file": "src/agent.ts",
          "line": 101
        },
        "event": {
          "type": "assistant_text",
          "delta": "已完成。文件中 `retries` 的值已从 **2** 改为 **3**，读取确认内容为：\n\n```ts\nexport const retries = 3\n```"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_d00d9edb9e2145ef90064c64",
                  "content": "edited /workspace/config.ts: replaced 11 chars"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_c497376af2ab40c19a013962",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/config.ts"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_c497376af2ab40c19a013962",
                  "content": "export const retries = 3\n"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "context-10",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_d00d9edb9e2145ef90064c64",
                  "content": "edited /workspace/config.ts: replaced 11 chars"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_c497376af2ab40c19a013962",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/config.ts"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_c497376af2ab40c19a013962",
                  "content": "export const retries = 3\n"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "text",
                  "text": "已完成。文件中 `retries` 的值已从 **2** 改为 **3**，读取确认内容为：\n\n```ts\nexport const retries = 3\n```"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-11",
        "label": "本轮结束：end_turn",
        "detail": "这一轮没有新的 tool_call，Agent Loop 正常退出。",
        "kind": "end",
        "source": {
          "file": "src/agent.ts",
          "line": 141
        },
        "event": {
          "type": "turn_end",
          "stopReason": "end_turn"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。严格按用户指定的工具顺序执行，完成后只报告最终值。",
          "messages": [
            {
              "role": "user",
              "content": "先用 edit 把 /workspace/config.ts 里的 retries = 2 改成 retries = 3，再用 read_file 读取同一文件确认。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_d00d9edb9e2145ef90064c64",
                  "name": "edit",
                  "input": {
                    "path": "/workspace/config.ts",
                    "old_string": "retries = 2",
                    "new_string": "retries = 3"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_d00d9edb9e2145ef90064c64",
                  "content": "edited /workspace/config.ts: replaced 11 chars"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_c497376af2ab40c19a013962",
                  "name": "read_file",
                  "input": {
                    "path": "/workspace/config.ts"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_c497376af2ab40c19a013962",
                  "content": "export const retries = 3\n"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "text",
                  "text": "已完成。文件中 `retries` 的值已从 **2** 改为 **3**，读取确认内容为：\n\n```ts\nexport const retries = 3\n```"
                }
              ]
            }
          ]
        }
      }
    ]
  },
  {
    "id": "tool-error",
    "number": "04",
    "title": "工具执行失败",
    "summary": "工具抛出错误，agent 把错误结果交还给模型。",
    "prompt": "查询离线包索引中 nanopi 的最新版本。",
    "model": "glm-5.2",
    "outcome": "错误成为 tool_result，模型仍能正常收尾。",
    "steps": [
      {
        "id": "input",
        "label": "用户消息进入 Context",
        "detail": "CLI 先把这一轮输入追加到 messages，随后把 Context 交给 runAgent()。",
        "kind": "input",
        "source": {
          "file": "src/cli.ts",
          "line": 49
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须调用唯一可用的工具；失败后用一句话说明失败原因。",
          "messages": [
            {
              "role": "user",
              "content": "查询离线包索引中 nanopi 的最新版本。"
            }
          ]
        }
      },
      {
        "id": "event-1",
        "label": "模型调用 lookup_package",
        "detail": "agent 收集工具名和参数，同时发出 tool_call 事件。",
        "kind": "tool",
        "source": {
          "file": "src/agent.ts",
          "line": 104
        },
        "event": {
          "type": "tool_call",
          "id": "call_9ca12d8e81c241b5a99c6378",
          "name": "lookup_package",
          "args": {
            "name": "nanopi"
          }
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须调用唯一可用的工具；失败后用一句话说明失败原因。",
          "messages": [
            {
              "role": "user",
              "content": "查询离线包索引中 nanopi 的最新版本。"
            }
          ]
        }
      },
      {
        "id": "context-2",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须调用唯一可用的工具；失败后用一句话说明失败原因。",
          "messages": [
            {
              "role": "user",
              "content": "查询离线包索引中 nanopi 的最新版本。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_9ca12d8e81c241b5a99c6378",
                  "name": "lookup_package",
                  "input": {
                    "name": "nanopi"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-3",
        "label": "lookup_package 返回结果",
        "detail": "工具已经执行完，结果先作为 AgentEvent 发出，随后写回 Context。",
        "kind": "error",
        "source": {
          "file": "src/agent.ts",
          "line": 132
        },
        "event": {
          "type": "tool_result",
          "id": "call_9ca12d8e81c241b5a99c6378",
          "name": "lookup_package",
          "result": "error: offline registry unavailable"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须调用唯一可用的工具；失败后用一句话说明失败原因。",
          "messages": [
            {
              "role": "user",
              "content": "查询离线包索引中 nanopi 的最新版本。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_9ca12d8e81c241b5a99c6378",
                  "name": "lookup_package",
                  "input": {
                    "name": "nanopi"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "id": "context-4",
        "label": "tool_result 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 172
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须调用唯一可用的工具；失败后用一句话说明失败原因。",
          "messages": [
            {
              "role": "user",
              "content": "查询离线包索引中 nanopi 的最新版本。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_9ca12d8e81c241b5a99c6378",
                  "name": "lookup_package",
                  "input": {
                    "name": "nanopi"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_9ca12d8e81c241b5a99c6378",
                  "content": "error: offline registry unavailable"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-5",
        "label": "模型流式输出文本",
        "detail": "stream() 产生 text_delta，agent 将它转成 assistant_text 发给界面。",
        "kind": "stream",
        "source": {
          "file": "src/agent.ts",
          "line": 101
        },
        "event": {
          "type": "assistant_text",
          "delta": "离线包索引查询失败，原因是离线注册表当前不可用（offline registry unavailable），请检查网络或离线索引服务状态后重试。"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须调用唯一可用的工具；失败后用一句话说明失败原因。",
          "messages": [
            {
              "role": "user",
              "content": "查询离线包索引中 nanopi 的最新版本。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_9ca12d8e81c241b5a99c6378",
                  "name": "lookup_package",
                  "input": {
                    "name": "nanopi"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_9ca12d8e81c241b5a99c6378",
                  "content": "error: offline registry unavailable"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "context-6",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须调用唯一可用的工具；失败后用一句话说明失败原因。",
          "messages": [
            {
              "role": "user",
              "content": "查询离线包索引中 nanopi 的最新版本。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_9ca12d8e81c241b5a99c6378",
                  "name": "lookup_package",
                  "input": {
                    "name": "nanopi"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_9ca12d8e81c241b5a99c6378",
                  "content": "error: offline registry unavailable"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "text",
                  "text": "离线包索引查询失败，原因是离线注册表当前不可用（offline registry unavailable），请检查网络或离线索引服务状态后重试。"
                }
              ]
            }
          ]
        }
      },
      {
        "id": "event-7",
        "label": "本轮结束：end_turn",
        "detail": "这一轮没有新的 tool_call，Agent Loop 正常退出。",
        "kind": "end",
        "source": {
          "file": "src/agent.ts",
          "line": 141
        },
        "event": {
          "type": "turn_end",
          "stopReason": "end_turn"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。必须调用唯一可用的工具；失败后用一句话说明失败原因。",
          "messages": [
            {
              "role": "user",
              "content": "查询离线包索引中 nanopi 的最新版本。"
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "tool_use",
                  "id": "call_9ca12d8e81c241b5a99c6378",
                  "name": "lookup_package",
                  "input": {
                    "name": "nanopi"
                  }
                }
              ]
            },
            {
              "role": "user",
              "content": [
                {
                  "type": "tool_result",
                  "tool_use_id": "call_9ca12d8e81c241b5a99c6378",
                  "content": "error: offline registry unavailable"
                }
              ]
            },
            {
              "role": "assistant",
              "content": [
                {
                  "type": "text",
                  "text": "离线包索引查询失败，原因是离线注册表当前不可用（offline registry unavailable），请检查网络或离线索引服务状态后重试。"
                }
              ]
            }
          ]
        }
      }
    ]
  },
  {
    "id": "max-tokens",
    "number": "05",
    "title": "撞上 max_tokens",
    "summary": "让长回答耗尽输出预算，观察截断后的结束事件。",
    "prompt": "请用至少两千个汉字解释 Agent Loop 为什么需要 Context。",
    "model": "glm-5.2",
    "outcome": "本轮没有工具调用，直接以 max_tokens 结束。",
    "steps": [
      {
        "id": "input",
        "label": "用户消息进入 Context",
        "detail": "CLI 先把这一轮输入追加到 messages，随后把 Context 交给 runAgent()。",
        "kind": "input",
        "source": {
          "file": "src/cli.ts",
          "line": 49
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。直接输出正文，不写标题，不省略内容。",
          "messages": [
            {
              "role": "user",
              "content": "请用至少两千个汉字解释 Agent Loop 为什么需要 Context。"
            }
          ]
        }
      },
      {
        "id": "context-1",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。直接输出正文，不写标题，不省略内容。",
          "messages": [
            {
              "role": "user",
              "content": "请用至少两千个汉字解释 Agent Loop 为什么需要 Context。"
            },
            {
              "role": "assistant",
              "content": []
            }
          ]
        }
      },
      {
        "id": "event-2",
        "label": "本轮结束：max_tokens",
        "detail": "模型碰到输出上限，agent 保留已收到的文本并结束本轮。",
        "kind": "end",
        "source": {
          "file": "src/agent.ts",
          "line": 141
        },
        "event": {
          "type": "turn_end",
          "stopReason": "max_tokens"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。直接输出正文，不写标题，不省略内容。",
          "messages": [
            {
              "role": "user",
              "content": "请用至少两千个汉字解释 Agent Loop 为什么需要 Context。"
            },
            {
              "role": "assistant",
              "content": []
            }
          ]
        }
      }
    ]
  },
  {
    "id": "abort-request",
    "number": "06",
    "title": "等待时按下 Ctrl+C",
    "summary": "请求刚发出就触发 AbortController，观察信号怎样结束本轮。",
    "prompt": "请详细列出一个 coding agent 从接收任务到完成任务的全部过程。",
    "model": "glm-5.2",
    "outcome": "fetch 停止，agent 发出 aborted。",
    "steps": [
      {
        "id": "input",
        "label": "用户消息进入 Context",
        "detail": "CLI 先把这一轮输入追加到 messages，随后把 Context 交给 runAgent()。",
        "kind": "input",
        "source": {
          "file": "src/cli.ts",
          "line": 49
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。回答要完整。",
          "messages": [
            {
              "role": "user",
              "content": "请详细列出一个 coding agent 从接收任务到完成任务的全部过程。"
            }
          ]
        }
      },
      {
        "id": "context-1",
        "label": "assistant message 写回 Context",
        "detail": "这次修改会进入下一轮请求，也会被 session 持久化。",
        "kind": "context",
        "source": {
          "file": "src/agent.ts",
          "line": 122
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。回答要完整。",
          "messages": [
            {
              "role": "user",
              "content": "请详细列出一个 coding agent 从接收任务到完成任务的全部过程。"
            },
            {
              "role": "assistant",
              "content": []
            }
          ]
        }
      },
      {
        "id": "event-2",
        "label": "本轮结束：aborted",
        "detail": "中断信号抵达当前任务，agent 清理未完成的数据后结束。",
        "kind": "end",
        "source": {
          "file": "src/agent.ts",
          "line": 110
        },
        "event": {
          "type": "turn_end",
          "stopReason": "aborted"
        },
        "context": {
          "systemPrompt": "你是 nanopi 的教学演示模型。回答要完整。",
          "messages": [
            {
              "role": "user",
              "content": "请详细列出一个 coding agent 从接收任务到完成任务的全部过程。"
            },
            {
              "role": "assistant",
              "content": []
            }
          ]
        }
      }
    ]
  }
];
